import type { Pack } from "../types";

export const unEco: Pack = {
  id: "un-eco",
  name: "Planet & Sustainability",
  description: "Climate, renewables, the UN & SDGs, wildlife, waste, and the people fighting for the planet.",
  categories: [
    {
      name: "Climate Change",
      clues: [
        { value: 200, clue: "This gas, CO2, is the main driver of human-caused global warming.", answer: "Carbon dioxide" },
        { value: 400, clue: "Melting land ice and warming oceans cause this slow-motion threat to coastal cities.", answer: "Sea level rise" },
        { value: 600, clue: "Thawing permafrost releases this greenhouse gas, ~80x more potent than CO2 over 20 years.", answer: "Methane" },
        { value: 800, clue: "The Paris Agreement aims to keep warming 'well below' 2°C, ideally to this figure.", answer: "1.5 degrees Celsius" },
        { value: 1000, clue: "This UN scientific body's assessment reports are the gold standard of climate science.", answer: "The IPCC (Intergovernmental Panel on Climate Change)" },
      ],
    },
    {
      name: "Renewable Energy",
      clues: [
        { value: 200, clue: "Photovoltaic panels turn this into electricity.", answer: "Sunlight (solar energy)" },
        { value: 400, clue: "These giant three-bladed towers harvest moving air.", answer: "Wind turbines" },
        { value: 600, clue: "Canada's biggest source of electricity, generated by falling water.", answer: "Hydroelectricity" },
        { value: 800, clue: "Iceland heats most of its homes with this energy from inside the Earth.", answer: "Geothermal energy" },
        { value: 1000, clue: "This dam on China's Yangtze River is the largest power station on Earth.", answer: "The Three Gorges Dam" },
      ],
    },
    {
      name: "The UN & the SDGs",
      clues: [
        { value: 200, clue: "The UN's headquarters sit beside the East River in this city.", answer: "New York City" },
        { value: 400, clue: "The SDGs are also called Agenda ____, for their target year.", answer: "2030" },
        { value: 600, clue: "The Sustainable Development Goals count this many goals.", answer: "17" },
        { value: 800, clue: "In climate summits like COP28, COP stands for this.", answer: "Conference of the Parties", dailyDouble: true },
        { value: 1000, clue: "This Portuguese diplomat has served as UN Secretary-General since 2017.", answer: "António Guterres" },
      ],
    },
    {
      name: "Wildlife & Biodiversity",
      clues: [
        { value: 200, clue: "Often called 'the lungs of the planet', this South American rainforest is the world's largest.", answer: "The Amazon" },
        { value: 400, clue: "This black-and-white bear is the WWF's logo.", answer: "The giant panda" },
        { value: 600, clue: "Bees, butterflies and bats do this job that makes a third of our food possible.", answer: "Pollination" },
        { value: 800, clue: "Warming seas cause this whitening stress reaction in reefs.", answer: "Coral bleaching" },
        { value: 1000, clue: "Sea otters and wolves are classic examples of this type of species whose loss collapses an ecosystem.", answer: "A keystone species" },
      ],
    },
    {
      name: "Recycling & Waste",
      clues: [
        { value: 200, clue: "Banana peels and coffee grounds belong in this bin to become soil.", answer: "Compost (the green bin)" },
        { value: 400, clue: "These plastic fragments under 5 mm have been found in rain, fish, and human blood.", answer: "Microplastics" },
        { value: 600, clue: "Old phones and laptops become this fastest-growing waste stream.", answer: "E-waste" },
        { value: 800, clue: "This 'patch' of floating plastic swirls in a gyre between California and Hawaii.", answer: "The Great Pacific Garbage Patch" },
        { value: 1000, clue: "Designing waste out from the start, this two-word model replaces the linear 'take, make, waste' system.", answer: "The circular economy", dailyDouble: true },
      ],
    },
    {
      name: "Famous Environmentalists",
      clues: [
        { value: 200, clue: "This Swedish activist started 'Fridays for Future' by skipping school at 15.", answer: "Greta Thunberg" },
        { value: 400, clue: "This British broadcaster narrated Planet Earth and Blue Planet.", answer: "Sir David Attenborough" },
        { value: 600, clue: "This primatologist spent 60+ years with the chimpanzees of Gombe.", answer: "Jane Goodall" },
        { value: 800, clue: "This Canadian scientist hosted CBC's 'The Nature of Things' for over 40 years.", answer: "David Suzuki" },
        { value: 1000, clue: "Her 1962 book 'Silent Spring' launched the modern environmental movement.", answer: "Rachel Carson" },
      ],
    },
  ],
  final: {
    category: "Global Agreements",
    clue: "Adopted in 2015 by 196 parties at COP21, this is the first universal, legally binding global climate treaty.",
    answer: "The Paris Agreement",
  },
};
